### ISSUE TITLE
Redis doesn't work with Moodle 3.1 (and likely 3.2 as well)

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/Moodle#119]
We identified an issue with Moodle 3.1 when it's deployed with a Redis cache in our templates. It appears to be a Moodle issue, not a Redis issue, because this issue doesn't repro with Moodle 3.4 (or other later versions). It may be related to [the Moodle issue](https://tracker.moodle.org/browse/MDL-55953) but can't confirm precisely at this moment. We'll need to find out what versions of Moodle are incompatible with Redis and document that in our templates. Failure logs pasted below.

```
May 22 16:36:09 vmss-nfuv3b000001 moodle: [Tue May 22 16:36:09.250973 2018] [:error] [pid 35166] [client 127.0.0.1:45204] Failed to connect to redis at redis-nfuv3b.redis.cache.windows.net:6379, error returned was: Failed to AUTH connection
May 22 16:36:09 vmss-nfuv3b000001 moodle: [Tue May 22 16:36:09.252688 2018] [:error] [pid 35166] [client 127.0.0.1:45204] Failed talking to redis: Failed to AUTH connection
```

**Comment by hosungsmsft** [comment]
Update: The actual Moodle issue is this: https://tracker.moodle.org/browse/MDL-58311

Tried workaround (by a partner) is to overwrite lib/classes/session/redis.php from Moodle 3.3 branch. Will try that out myself.

**Comment by rgardler** [comment]
Marked a P2 as this is an upstream issue and only exists in older versions of Moodle. Happy to accept patches if anyone is facing this issue.

**Comment by hosungsmsft** [comment]
Agreed. The Moodle bug tracker page says "Fixed Branches:
MOODLE_33_STABLE", so I suppose this issue will be there on Moodle 3.2 as well. Not sure, though, if this is a bug on us? Our templates could/should be more intelligent and checking this kind of incompatibility, but I'm not sure if we can do something like that with ARM language?

**Comment by rgardler** [comment]
If there are many of these parameter incompatibilities we could consider providing a tool that will look at your properties file and warn of known issues. This could be a wrapper around the AZ CLI (or even an AZ CLI module) that would validate the parameters and perform the deployment in a single command.

That said, I'm just thinking aloud. I don't see this as a particularly hi priority item. If we get too many users hitting failures we could revisit solutions.

**Comment by enovationIT** [comment]
I can confirm 3.2 is affected, this is because redis requires authentication for sessions and that was only introduced in 3.3.

**Comment by aspark21** [comment]
Considering anything below Moodle 3.5 is now EOL since May 2019 this issue can be closed
