### ISSUE TITLE
Clamd installation and config for upload

### ISSUE THREAD

**Issue by enovationIT** [Azure/Moodle#125]
adding antivirus on all web servers and enabling upload scanning

**Comment by rgardler** [comment]
Quoting @hosungs from #128 (unrelated but possibly overlapping solution):

How about utilizing the script hook that's implemented in #120 by @dlm-sadge ? I think you can install any packages you want on the VMSS VMs post-deployment, using the facility. Would you let us know if you try this and have any results? How to use the hook is documented in the PR and hopefully that's enough for you. Thanks!

**Comment by enovationIT** [comment]
the hook approach works for this as well with the same performance implication as per my comment in #128
