### ISSUE TITLE
Enable additional configuration of Web Tier post deployment

### ISSUE THREAD

**Issue by enovationIT** [Azure/Moodle#128]
would it be possible to include php-ssh2 and php-mcrypt in the extension? we have it already implemented for a customer, but was wondering if it could be added in general? ( we can do the pull request in the spirit of scratching own itch as at the moment I need to use artefacts from another server as opposed to directly from here)

**Comment by hosungsmsft** [comment]
How about utilizing the script hook that's implemented in #120 by @dlm-sadge ? I think you can install any packages you want on the VMSS VMs post-deployment, using the facility. Would you let us know if you try this and have any results? How to use the hook is documented in the PR and hopefully that's enough for you. Thanks!

**Comment by enovationIT** [comment]
I'm not sure I understand, is the plan to have some php extensions installed by deployment scripts and then any additional ones using this hook manually after the deployment?

**Comment by hosungsmsft** [comment]
I don't think there's a firm/fixed plan on the PHP extensions installation, but certainly we can't install all possible PHP extensions at the VM creation time, so I suppose any PHP extensions that are not installed at the VM creation time but are needed by individual customers will need to be installed by some means like the hook. We'll also start considering any design alternatives on this, and any suggestions are welcome and appreciated.

**Comment by enovationIT** [comment]
We have used this approach and it works fine. The only issue with it I found in a custom setup with more extensions required when a VM joins the web cluster it doesn't have all that's required and on a busy system requests are already coming and errors start showing very quickly to the end users. 
To get an error free and efficient autoscaling the second the vm joins the cluster it needs to be ready to serve the application, so ideally to speed up the process and have it error free - a custom image should be maintained and only a minimum config happening on autoscaling.

**Comment by rgardler** [comment]
There is a new mechanism, called [image builder] (https://azure.microsoft.com/en-us/blog/announcing-private-preview-of-azure-vm-image-builder/), for building custom images on Azure. It's in preview right now, but I believe it will help with your performance issues.

We don't currently have plans to add support for custom images, but there is no reason I can think of that would prevent the acceptance of a patch.
