### ISSUE TITLE
Nginx fails to start after reboot/restart

### ISSUE THREAD

**Issue by enovationIT** [Azure/Moodle#130]
nginx tries to start and load the cert before gluster share is mounted, fails not being able to load the cert

**Comment by hosungsmsft** [comment]
Thanks for letting us know this issue, which is another oversight on our end... (poor excuse that we've always just created/deleted VMSS VMs, not restarted any of them) This will require some change in the nginx service config, or maybe copy the cert files to a local file system (like php files). All in all, it's evident that our entire config story needs significant improvement, and we'll definitely address this issue either separately & independently for now, or for the long term with the config story improvement. All in all, your PR for this fix would be greatly appreciated.
