### ISSUE TITLE
When deploying Maximal Deployment An error occurs due to installElasticSearchSwitch

### ISSUE THREAD

**Issue by taylora3** [Azure/Moodle#141]
In order to get the maximal deployment to work I had to remove the parameter installElasticSearchSwitch from the template. I believe that it is in azuredeploy-maximal.json. on line 38

                    "installElasticSearchSwitch":   { "value": true },

> "code":"InvalidTemplate","message":"Deployment` template validation failed: 'The template parameters 'installElasticSearchSwitch' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time.

**Comment by rgardler** [comment]
Thanks for the report, looks like the parameters file for maximal deployment want updated with a recent change to the search install method. The correct parameters are listed in https://github.com/Azure/Moodle/blob/master/docs/Parameters.md#search type. I'm on phone rig now so can't update and test the file, but will do it soon.

**Comment by hosungsmsft** [comment]
Thanks for reporting this issue, and you are right @rgardler. A fix is coming very soon and it will auto-close this issue.
