### ISSUE TITLE
Moodle install fails when launching from Readme link

### ISSUE THREAD

**Issue by mattporritt** [Azure/Moodle#142]
Tried to deploy Moodle using the “deploy to Azure” button in the project Readme to deploy a “Large size deployment” into the US East Azure region. The stack seemed to work (18 deployments successful) however Moodle was not installed. When I went to the URL of the load balancer I received  the Moodle installation page. The same issue occurred when I tried the “deploy to Azure” button on the small to mid size deployment.

Tried this with US west and US east regions. Also tried a few hours apart to try and rule out an intermittent issue.

We’ll have a look into this on our end, raising an issue for visibility on our end.

**Comment by hosungsmsft** [comment]
This was a regression from #140 and is now fixed with the commit c872999e1e98b2f6014b3b315bb2878ce584d332. I'm closing this issue as such. Please reopen this issue if the issue still persists.
