### ISSUE TITLE
Moodle install fails when using Postgres

### ISSUE THREAD

**Issue by mattporritt** [Azure/Moodle#143]
Tried to deploy the stack to US West Azure region using Postgres as the database via Azure CLI and instructions at https://github.com/Azure/Moodle/blob/master/docs/Deploy.md This way  did not successfully setup and install Moodle. The stack seemed to work (no obvious errors in output JSON) however Moodle was not installed. When I went to the URL of the load balancer I received the Moodle installation page.

I set Postgres as the database in the Azure parameters json file. I then tried the same procedure using the default MSSQL database and the stack built successfully. A subsequent test build again using Postgres also failed to install Moodle.

We’ll have a look into this on our end, raising an issue for visibility.

**Comment by hosungsmsft** [comment]
This was a regression from #140 and is now fixed with the commit c872999e1e98b2f6014b3b315bb2878ce584d332. I'm closing this issue as such. Please reopen this issue if the issue still persists.
