### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#148]
Hey,

I'm trying to add a plugin form the moodle plugin directory (https://moodle.org/plugins/index.php).

After downloading one (block progress) when I go to upload it I get permission issues.
![image](https://user-images.githubusercontent.com/2485554/41659796-35eacf24-7492-11e8-9b35-af79327ad965.png)

I'm logged in as admin.

Mark as delete after reading documentation "Managing a Scalable Moodle Cluster in Azure"

**Comment by hosungsmsft** [comment]
Hi @tiberain,

Installing a plugin is modifying the installed Moodle code, and on our templated solutions, we currently don't allow plugin installation through the web browser. Users must install plugins by copying the directory over to the controller VM's `/moodle/html/moodle/...` directory and initiate replication to the web frontend VMs. This is all documented [here](https://github.com/Azure/Moodle/blob/master/docs/Manage.md#updating-moodle-codesettings), though we probably should have mentioned that plugin installations fall into this case as well.

This is enforced by the command in the install script at [this line](https://github.com/Azure/Moodle/blob/master/scripts/install_moodle.sh#L895). As you can see, the ownership of the entire directory `/moodle/html/moodle` is changed to root, which makes the web server processes (whose user id is www-data) unable to write to that directory. We believe this is the best practice for scalable Moodle deployment with multiple web server machines and it was as is as delivered from the original Moodle partner who modernized the entire templates. Unfortunately, that makes plugin installations through web browsers impossible like this. We are open to make this optional if there are sufficiently many requests from customers, but we must say it's not going to be a good security practice.
