### ISSUE TITLE
Modify siteUrl and/or run moodle under multiple URLs

### ISSUE THREAD

**Issue by Smilebags** [Azure/Moodle#158]
I have recently deployed the Minimal template and didn't specify the siteURL because it was not yet decided. I now wish to modify the siteUrl of the deployment and if possible, work out how to create aliases for the site.

I have CNAME records pointing to the load balancer for the desired URL, and have modified the `controller-vm:/etc/apache2/sites-enabled/000-default.conf` to include the desired siteUrl as the ServerName, but I still get redirected to the load balancer URL. Is this azure, the load balancer, or Moodle causing this redirection? How can I modify the siteUrl after creating the resource group?

**Comment by hosungsmsft** [comment]
Hi Chris,

It's not Azure or the load balancer, but the Moodle itself. You need to update the `$CFG->wwwroot` definition in your Moodle's `config.php`, which should reside in `/moodle/html/moodle`. After updating your `config.php` for the new `$CFG->wwwroot` URL, you need to also let all VMSS instance VMs take that change by issuing the command `sudo /usr/local/bin/update_last_modified_time.moodle_on_azure.sh` on your controller VM (after which every VMSS instance VM will sync the change on its local disk). Please try this and let us know how it went.

Thanks!

**Comment by Smilebags** [comment]
Hi @hosungsmsft ,

Thank you, that has worked a charm. I had actually tried modifying that file, but I just missed the update step so the changes weren't propagated. Maybe there's the opportunity for some documentation regarding this? I read through the documentation linked from the homepage of this repo but from what I read, couldn't find anything about this very useful command. If this is indeed mentioned in the documentation, sorry, I must have missed it.

Thanks for the quick reply, you've helped a lot.

**Comment by hosungsmsft** [comment]
Thanks for letting us know it worked and also for your feedback. Sorry it's documented [here](https://github.com/Azure/Moodle/blob/master/docs/Manage.md#if-you-set-htmllocalcopyswitch-to-true-this-is-the-default-now), but it's kind of buried. It'd be great if you send a PR to our repo for a good proposed change of this documentation as you see fit.
