### ISSUE TITLE
Loading new themes 

### ISSUE THREAD

**Issue by Antwune** [Azure/Moodle#159]
This may be a very silly question, but I've attempted to load new themes via the controller VM with no success in making them visible in the front end web server.  I've created a folder within /moodle/html/moodle/theme called contemporary.  I've used PSCP to copy the contents from the zipped them controller.  I've even restarted the web server in hopes to force a sync from the controller's /moodle folder to the webserver's /var/www/html/moodle/theme folder.  Is anyone else having this problem?  I've been working on this for 2 days with no success.

Thank a million!

**Comment by rgardler** [comment]
You need to run a  script to trigger the copy to the public VMs. See the documentation on cluster management - specifically https://github.com/Azure/Moodle/blob/master/docs/Manage.md#updating-moodle-codesettings
