### ISSUE TITLE
Add latest version number (3.4.1) to allowed values for Moodle version

### ISSUE THREAD

**Issue by rgardler** [Azure/Moodle#16]
Moodle has released version 3.4.1, we should add it to the templates.

**Comment by hosungsmsft** [comment]
Isn't it that we just need to change the "moodleVersion" parameter value to "v3.4.1"? That's my understanding from looking at the {mysql,postgres}_install_moodle.sh scripts, but I haven't tested that yet.

The default value of "moodleVersion" param value is "MOODLE_34_STABLE", and I can't find the entry MOODLE_34_STABLE.zip in the GitHub.com/moodle/moodle/releases, but for some reason, it's downloaded just fine.

**Comment by rgardler** [comment]
Since this will be the first time we've done this part of the outputs should be documenting the process. For a minor version it should be very simple, as you suggest. But until we do it we can't be sure.

**Comment by hosungsmsft** [comment]
I actually browsed the git commit graph, and realized that "MOODLE_34_STABLE" is a branch (which moves all the time), and "v3.4.1" is a tag (which is fixed). As of now (1/29/2018), "MOODLE_34_STABLE" is past "v3.4.1", so a default deployment of our current template will install Moodle ver. 3.4.1. I think this issue can be closed as such, unless you wanted to add a tag (fixed) "v3.4.1" to our moodle version parameter values.

**Comment by rgardler** [comment]
I think it is a good idea to have the default a fixed release in a known state. If MOODLE_34_STABLE is the latest dev release then this should be available but not the default.

I'll update the title and move this to v1.2

**Comment by hosungsmsft** [comment]
Just wanted to mention that MOODLE_*_STABLE branches don't seem to be the latest dev branches, but they are release branches for the stable versions. However, they are branches, so they are not fixed for sure.

**Comment by nimojg-microsoft** [comment]
Moodle is now on version 3.4.2 (see [here](https://moodle.org/mod/forum/discuss.php?d=367479))

**Comment by rgardler** [comment]
Thanks for the update. @hosungsmsft if I understand your previous comment our templates will continue automatically be deploying the 3.4.2 version with no changes.

However, we ought to update the acceptable version number to explicitly allow 3.4.1.
