### ISSUE TITLE
Post Deployment SSL

### ISSUE THREAD

**Issue by Antwune** [Azure/Moodle#160]
Are there steps available for installing an SSL cert post deployment?  I don't suppose copying the the certificate into the nginx.crt and.key files is going to work.

**Comment by rgardler** [comment]
There is no built in support for this (or for renewing certs post deployment). You'll need to manually update the deployed certificate and private key files (/moodle/certs/nginx.{crt,key} on the controller VM) and restart all the web frontend VM instances. We'll improve our implementation to support auto-rotation in the future.

**Comment by rgardler** [comment]
Closing as I'm assuming the above answered your question. If not feel free to reopen and ask further questions.

**Comment by dosnet6070** [comment]
How to configure SSL for below instance,

Large size deployment (with high availability) | Supporting more than 2000 concurrent users. This deployment will use Gluster (for high availability, requiring 2 VMs), MySQL (16 vCores) and redis cache, without other options like elastic search.
-- | --
