### ISSUE TITLE
rotating certs

### ISSUE THREAD

**Issue by tiberain** [Azure/Moodle#162]
Hey,

My current solution uses app gateway and for the cert at deployment I used the azure key vault, this all worked fine. I also updated the cert on the app gateway and that worked fine as well.

So my cert expired a few weeks ago and I've got the new ones updated the key vault and app gateway. But when I went to /moodle/certs its empty. Where do I need to update this on moodle to update the cert or do I just add the new cert in here?
![image](https://user-images.githubusercontent.com/2485554/47915714-a25b7500-de9b-11e8-86c6-44575900cd65.png)

**Comment by rgardler** [comment]
While I haven't done this myself I believe you need to change the certs on the controller VM as you describe, then run the script to [copy the content to the front-end VMs](https://github.com/Azure/Moodle/blob/master/docs/Manage.md#if-you-set-htmllocalcopyswitch-to-true-this-is-the-default-now) and restart the front-end VMs.

Please let us know if this works for you, ideally as a PR against our docs, but as a comment here will still be appreciated.

**Comment by tiberain** [comment]
@rgardler sorry if I explained this wrong but where are the cert on the controller as you can see form the above screenshot the /moodle/certs/ folder is empty. I was able to update the app gateway cert in azure with no problem.

**Comment by rgardler** [comment]
Hah! Of course, I want thinking straight. Thanks for following up.

**Comment by tiberain** [comment]
Hey,

I'm wondering if this issue can be reopened, as the way to rotate the cert on an app gateway seemed to have changed.
This used to be done by updating the cert in the **Key Vaut** but now it seems you have to update the cert in the 

> Application gateway -> Frontend IP Configuration -> public Config

This is the place you need to upload your pfx now it seems
