### ISSUE TITLE
DNS integration for managed application

### ISSUE THREAD

**Issue by enovationIT** [Azure/Moodle#163]
Currently a deployment from service catalog with default azuredeploy uses the load balancer's name for the Moodle wwwroot, is there an option to integrate somehow with a hosted zone on azure and pull a name from there  i.e. hosted zone testmoodle.com and then ask using the form for something and deploy with something.testmoodle.com?

**Comment by rgardler** [comment]
I'm sorry this seems to have been missed completely, but better late than never.

Yes, it is possible to set the URL for deployment see https://github.com/Azure/Moodle/blob/master/docs/Parameters.md#siteurl
