### ISSUE TITLE
Couldn't we replace GlusterFS with an Azure Files share..?

### ISSUE THREAD

**Issue by mtwelve** [Azure/Moodle#169]
Hi,

Couldn't we replace GlusterFS with an Azure Files share that is then presented to the web servers?

I'm trying to think of the simplest HA design and I don't currently have any experience with GlusterFS.

Regards
Sam

**Comment by rgardler** [comment]
If you dig deep enough into the templates you will find that they do actually support Azure Files. However, because of the way Moodle works with files and the performance optimization choices in Azure Files the two do not play well together. Therefore this feature has not been exposed in a documented way.

**Comment by munir94** [comment]
hello , 
does the iops is the issue ? anyway i could see how to properly mount the azure file for experience purposes as i still failed doing it in my test lab

**Comment by UmakanthOS** [comment]
Munir,

IOPs was an issue for Azure Files Standard. The recommendation is to use Azure Files Premium. The Moodle template is now being updated to use Azure Files Premium as default and the changes should be published within a week, if not sooner.

Meanwhile, if you do want to try out Azure Files Premium, please [provision an Azure Files Premium file](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-premium-fileshare) share inside an Azure Storage account. Once you've done that, follow the below series of steps on the Moodle controller VM:

1. Ensure you have a backup of your Moodle location (/moodle) and put your Moodle site in maintenance mode

2. Run the commands in the below order:
- umount /moodle
- sudo apt install cifs-utils
- mv /moodle /moodle_old

3. For the Azure Files Premium share you created, get storage account name (the one you've used to create your Azure Storage account, let's call that STORAGEACCT) and storage account key from the Azure Portal or using Azure CLI:

STORAGEKEY=$(az storage account keys list \
    --resource-group "myResourceGroup" \
    --account-name $STORAGEACCT \
    --query "[0].value" | tr -d '"')

4. As root or with sudo privileges, save these credentials to a file, set proper permissions to the file

cat <<EOF > /etc/moodle_azure_files.credential
username=$STORAGEACCT
password=$STORAGEKEY
EOF

chmod 600 /etc/moodle_azure_files.credential

5. Create a new shell-script file (call it azfpremsetup.sh) and copy the contents over:

#!/bin/bash
    grep -q -s "^//$storageAccountName.file.core.windows.net/moodle\s\s*/moodle\s\s*cifs" /etc/fstab && _RET=$? || _RET=$?
    if [ $_RET != "0" ]; then
        echo -e "\n//storageAccountName.file.core.windows.net/FileStorageName   /moodle cifs    credentials=/etc/moodle_azure_files.credential,uid=www-data,gid=www-data,nofail,vers=3.0,dir_mode=0770,file_mode=0660,serverino,mfsymlinks" >> /etc/fstab
    fi
    mkdir -p /moodle
    mount /moodle
Once you save the file and run the shell-script, the Azure File share you've created should be mounted. Now all that's left is to copy over the contents of your Moodle directory. 

6. cp -a /moodle_old/* /moodle || true

Once the copying is done, check any relevant cron jobs are running as expected, pull the site out of maintenance mode and run your usual smoke/functional tests. Once you're sure everything is working, you can get rid of your /moodle_old path (you did back it up, yes?)

Finally, an updated template will be made available very soon. The above steps can be used for manual testing in the meantime or if you already have an existing Moodle installation on gluster or nfs-noha or any other filesystem that you'd like to migrate to an Azure Files Premium file share.

**Comment by munir94** [comment]
sorry i been hit by failed to parse the mount option. any thought of it ?  
#!/bin/bash
grep -q -s "^//prodmddata01.file.core.windows.net/moodle\s\s*/moodle\s\s*cifs" /etc/fstab && _RET=$? || _RET=$?
if [ $_RET != "0" ]; then
echo -e "\n//prodmddata01.file.core.windows.net/FileStorageName /moodle cifs credentials=/etc/moodle_fs.credential,uid=apache,gid=apache,nofail,vers=3.0,dir_mode=0770,file_mode=0660,serverino,mfsymlinks" >> /etc/fstab
fi
mkdir -p /moodle
mount /moodle

**Comment by ummadisudhakar** [comment]
prodmddata01.file.core.windows.net/FileStorageName /moodle ...its only //prodmddata01.file.core.windows.net/moodle..remove 
FileStorageName and try

**Comment by ummadisudhakar** [comment]
prodmddata01.file.core.windows.net/FileStorageName /moodle ...its only //prodmddata01.file.core.windows.net/moodle..remove 
FileStorageName and try

**Comment by munir94** [comment]
manage to get it mount, sadly moodle could not right onto it.
![image](https://user-images.githubusercontent.com/39366930/88077333-beda9c00-cbad-11ea-81ab-3bc409c526f4.png)

**Comment by rgardler** [comment]
Recently a PR to add Azure Premium Files support was merged: https://github.com/Azure/Moodle/pull/193
