### ISSUE TITLE
Plugin installation Fails

### ISSUE THREAD

**Issue by alxdean** [Azure/Moodle#170]
Hi, 
I've been able to get the small-mid sized template to install in the westus region. Took me a moment to figure out where the resulting urls and passwords are, but all good there. 
Now I'm trying to install a plugin and it simply won't work. Any plugin:

Validating <pluginname> ... Error
  [Error] Write access check [/var/www/html/moodle/<folder>] 
Installation aborted due to validation failure

the thing that stumps me is:
that folder does not exist. Moodle is installed in /moodle/html/moodle and not /var/www

I've tried creating a symlink
ln -s /var/www/html/moodle/ /moodle/html/moodle/

but that did not help either

I've tried 
sudo chown daemon:www-data /moodle/html/moodle

sudo chmod 755 /moodle/html/moodle
also tried
sudo chmod 777 /moodle/html/moodle

even tried creating the damn thing
sudo mkdir /var/www/html/moodle
and then setting permissions
sudo chmod 755 /var/www/html/moodle
and then owning it
sudo chown daemon:www-data /var/www/html/moodle

I've not been able to figure out why the plugin installer tries to copy the files into the wrong folder. Is there a DB config issue with the latest template?

**Comment by nelsontalag** [comment]
what is the plugin that you are installing ?

**Comment by rgardler** [comment]
@nelsontalag the answer to your question is in the original report "Any plugin"

@alxdean can you please confirm that you are trying to install the plugin as documented: https://github.com/Azure/Moodle/blob/master/docs/Manage.md#updating-moodle-codesettings

If you are continuing to see problems please provide a step by step description of what you are doing so that we can reproduce.

**Comment by rgardler** [comment]
I just realized this was originally reported Oct 2019. We'll leave this open to give Alex a chance to respond if he is still active, otherwise we will close the issue.

**Comment by UmakanthOS** [comment]
@alxdean Please do re-open the issue if possible around plugin details/approach.

**Comment by alxdean** [comment]
Hi. no need to re-open. I gave up, especially as I did not get a timely response here, and installed moodle from scratch on a linux machine. That worked a charm. just the azure vm template was buggy, as it kept trying to install plugins into the wrong folder.

**Comment by UmakanthOS** [comment]
Thanks for the update @alxdean 

Apologies for the shoddy experience with the template.
