### ISSUE TITLE
VM has reported a failure when processing extension 'setup_moodle'

### ISSUE THREAD

**Issue by mosalah82** [Azure/Moodle#171]
I got an error during scaleSetTemplate deployment, can anyone help on that please?

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'setup_moodle'
[moodle.docx](https://github.com/Azure/Moodle/files/3746529/moodle.docx)
. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nHit:1

**Comment by sergiorru** [comment]
Hi did you solved this issue?
