### ISSUE TITLE
moodle administration page turback an error message "Invalid permissions detected when trying to create a directory"

### ISSUE THREAD

**Issue by ahamdy-aou** [Azure/Moodle#172]
Hi all 
we faced an issue while using moodle-azure template , that we can not reach site administration pages giving an error message
**"Invalid permissions detected when trying to create a directory"** 
![iss](https://user-images.githubusercontent.com/57170399/67839533-ef047b00-fb04-11e9-9fb6-16a1d5039f35.png)

we use template since one week and all was good , we did not change any of directories permissions  
So have anyone faced and solve this issue before?

**Comment by rgardler** [comment]
There should be nothing about Azure that will change the permissions on your files and certainly nothing in the template that will do so. This would seem to be a Moodle issue. I suggest you raise this issue with the Moodle community.
