### ISSUE TITLE
Updating TLS settings to only TLS 1.2 to meet new security requirements?

### ISSUE THREAD

**Issue by mgancarzdsi** [Azure/Moodle#178]
It looks like the current SSL configuration allows TLS 1.0, 1.1 and 1.2. In 2020, this does not meet security requirements anymore.
https://github.com/Azure/Moodle/blob/898446de4154d330ce7bb4615923b747c14658e2/scripts/install_moodle.sh#L299

https://github.com/Azure/Moodle/blob/75d15167504966a94bcf67302be29a80e775e82d/scripts/setup_webserver.sh#L158

Would specifying the following parameters in install_moodle.sh and setup_webserver.sh help meet these requirements?
```
  ssl_protocols TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
```

**Comment by UmakanthOS** [comment]
Thanks Mathew. Looking into testing these changes on our end first and will update this topic with our findings.

**Comment by ummadisudhakar** [comment]
Changes related to TLS upgrade are in and tested.Can close this issue.
