### ISSUE TITLE
Need support in upgrading moodle to v3.8

### ISSUE THREAD

**Issue by ravish0007** [Azure/Moodle#179]
Hello there, I need some tips in upgrading my Moodle deployment before  my experimentation mess up the deployment. first time with Glusters.

**Comment by ravish0007** [comment]
moved  ....../html/moodle to ......./html/moodle-original. 
Downloaded moodle source and copied config.php from moodle-original to moodle(new).

Restarted VM's  still No change. Anything need to be donw ?

**Comment by rgardler** [comment]
This is an open source project, there is no support - sorry. Of course we can help guide you in the right direction so you can support yourself. It would be great to have you update the templates and docs when you succeed.

If you want to upgrade in-place then you need to follow the Moodle documentation on upgrading. The documentation in https://github.com/Azure/Moodle/blob/master/docs/Manage.md will guide you on what you need to do to get the right version of Moodle onto your cluster.

The easiest way to upgrade is to simply cahnge the templates to support the new version, redeploy and then connect an existing DB and Filestore. Assuming no new requirements from Moodle this is a simple case see https://github.com/Azure/Moodle/pull/118/commits

**Comment by UmakanthOS** [comment]
Moodle 3.8 is now the default version of Moodle deployed by the template. In addition 3.9 is also available to install (fully configurable option).
