### ISSUE TITLE
error/Unable to obtain session lock 

### ISSUE THREAD

**Issue by ravish0007** [Azure/Moodle#180]
I tried upgrading moodle to v3.8 and restarted my VMs, getting "error/Unable to obtain session lock ", How to resolve this ?, Please Help !

**Comment by UmakanthOS** [comment]
What template are you using? What version of PHP are you using with Moodle 3.8? What are you rmemcached settings? What about your debug logs? (Keep in mind the templates default to the system log and don't have Moodle/PHP writing to separate log files).

**Comment by rgardler** [comment]
See my answer to #179. It seems @ravish0007 has not correctly upgraded to v3.8. This error is almost certainly a symptom of that failed upgrade.

I'm going to close this issue. If an upgrade is achieved and this error persists then re-open.
