### ISSUE TITLE
General Exception

### ISSUE THREAD

**Issue by ravish0007** [Azure/Moodle#181]
I faced this general exception and no idea what this is.
![e](https://user-images.githubusercontent.com/32391963/78744508-5b6e8a80-797f-11ea-8aa7-77792a0797d9.png)

**Comment by UmakanthOS** [comment]
As mentioned in one of the other issues, there's no support available for Moodle here. From this issue and your other issues, I suspect your PHP version is suspect. Recommend you follow Moodle documentation and best practices here.
