### ISSUE TITLE
Minimal Deployment (Portal)

### ISSUE THREAD

**Issue by hamboneZA** [Azure/Moodle#191]
Hello! Any ideas on this error? Thanks for the help!

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"Conflict\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"status\\\\\\\": \\\\\\\"Failed\\\\\\\",\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"ResourceDeploymentFailure\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\\",\\\\r\\\\n \\\\\\\"details\\\\\\\": [\\\\r\\\\n {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"VMExtensionProvisioningError\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"VM has reported a failure when processing extension 'install_moodle'. Error message: \\\\\\\\\\\\\\\"Enable failed: failed to execute command: command terminated with exit status=1\\\\\\\\n[stdout]\\\\\\\\n\\\\\\\\n[stderr]\\\\\\\\nacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\\\\\\\\n+ sudo apt-get -y update\\\\\\\\n+ sudo apt-get install -y --force-yes graphviz aspell php-common php-soap php-json php-redis\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\\\\\\\\n+ sudo apt-get install -y --force-yes php-bcmath php-gd php-xmlrpc php-intl php-xml php-bz2 php-pear php-mbstring php-dev mcrypt\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\\\\\\\\n++ get_php_version\\\\\\\\n++ '[' -z '' ']'\\\\\\\\n+++ /usr/bin/cut -c 1,2,3\\\\\\\\n+++ /usr/bin/php -r 'echo PHP_VERSION;'\\\\\\\\n++ _PHPVER=7.0\\\\\\\\n++ echo 7.0\\\\\\\\n+ PhpVer=7.0\\\\\\\\n+ '[' mssql = mysql ']'\\\\\\\\n+ '[' mssql = mssql ']'\\\\\\\\n+ sudo apt-get install -y libapache2-mod-php\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\n+ install_php_mssql_driver\\\\\\\\n+ apt-key add -\\\\\\\\n+ /usr/bin/curl https://packages.microsoft.com/keys/microsoft.asc\\\\\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0\\\\\\\\r100 983 100 983 0 0 669 0 0:00:01 0:00:01 --:--:-- 669\\\\\\\\n+ /usr/bin/curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list\\\\\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r100 79 100 79 0 0 82 0 --:--:-- --:--:-- --:--:-- 82\\\\\\\\n+ sudo apt-get update\\\\\\\\n+ sudo ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools unixodbc-dev -y\\\\\\\\ndebconf: unable to initialize frontend: Dialog\\\\\\\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\\\\\\\ndebconf: falling back to frontend: Readline\\\\\\\\ndebconf: unable to initialize frontend: Readline\\\\\\\\ndebconf: (This frontend requires a controlling tty.)\\\\\\\\ndebconf: falling back to frontend: Teletype\\\\\\\\ndpkg-preconfigure: unable to re-open stdin: \\\\\\\\n+ echo 'export PATH=\\\\\\\\\\\\\\\"$PATH:/opt/mssql-tools/bin\\\\\\\\\\\\\\\"'\\\\\\\\n+ echo 'export PATH=\\\\\\\\\\\\\\\"$PATH:/opt/mssql-tools/bin\\\\\\\\\\\\\\\"'\\\\\\\\n+ source /root/.bashrc\\\\\\\\n++ '[' -z '' ']'\\\\\\\\n++ return\\\\\\\\n++ sed -e 's|.*:\\\\\\\\\\\\\\\\s*||'\\\\\\\\n++ grep 'Loaded Configuration'\\\\\\\\n++ php --ini\\\\\\\\n+ /usr/bin/pear config-set php_ini /etc/php/7.0/cli/php.ini system\\\\\\\\n+ /usr/bin/pecl install sqlsrv\\\\\\\\n\\\\\\\\\\\\\\\"\\\\\\\\r\\\\\\\\n\\\\\\\\r\\\\\\\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \\\\\\\"\\\\r\\\\n }\\\\r\\\\n ]\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}`

**Comment by rgardler** [comment]
@hamboneZA did you close this because it worked on a subsequent deployment? We have had reports of intermittent failures that look identical to this. If you are able to provide any more details (config options, region etc.) that would be very helpful.

**Comment by rgardler** [comment]
I now see you commented on the existing open issue at #167 . Thank you for moving your concern there. Any additional info you can provide will help us get to the bottom of this intermittent problem

**Comment by UmakanthOS** [comment]
@hamboneZA Please re-open if you're still seeing this issue. There's been several updates to the template in the last 9 odd months around performance optimizations and improved reliability. I just tested out the minimal deployment in North EU, Western EU and West US 2 and there's no issues with deployment.
