### ISSUE TITLE
Large deployment moodle/ permission issues

### ISSUE THREAD

**Issue by joseluisrc** [Azure/Moodle#196]
I've successfully deployed and completely configured a "Small to Mid-Sized" Azure-Moodle site. I've logged in through SSH and changed Moodle code when necessary.

Now, I need to deploy a "Large" installation. The deployment went perfect but when I ssh'ed into the controller, the file permissions seem to be wrong. I can't cd into /moodle/. The folder /moodle/ has www-data:www-data ownership and the permissions on this folder are 760. On the "Small to Mid-Sized" installation, this folder has root:root ownership and 755 permissions.

Curiously, the "Large" installation has a folder called **/moodle_old_delete_me/** which I can cd into and it seems identical to the normal /moodle/ folder.

I can't change azureadmin's groups, nor can I change /moodle/ ownersship.

It seems to be a problem with the template. Has someone else solved it?

Thanks!

**Comment by UmakanthOS** [comment]
Looking into this. Thanks for flagging this with us.

**Comment by joseluisrc** [comment]
I tried using the Maximum installation and it has the same problem.

**Comment by UmakanthOS** [comment]
For Maximal and Large today, older code was being used where the initial directory creation and configuration (/moodle and everything under it) was being done on a local disk, then an Azure Files Premium share was being created, mounted and a copy was being done to the mounted Azure share. This is obviously clunky and messy and currently testing a change to create an Azure Files share, mount the share and then work out of that share.

This eliminates the clunky copy and the need to delete the older /moodle directory. Around permissions, it should be www-data and this is being handled for Large and Maximal differently as the permissions are being explicitly set during share creation (previously Gluster, now Azure Files) which isn't happening for the "small to mid" which uses a local NFS share. There's a need to be consistent here...

**Comment by joseluisrc** [comment]
Thanks so much for your insight. I've looked through the scripts and they're very complex. I could see there being bugs because testing them could be very difficult.

Now, I need to be practical. As this installation is quite urgent, is there a "simple" solution to this problem, or should I look elsewhere for a large Moodle installation deployment?

Thanks!

**Comment by UmakanthOS** [comment]
For the large and maximal today, you can just manually delete the older  /moodle_old_delete_me/  and be on your merry way. The older code contained a line to remove that directory but it was commented out. I ran a stress test against the current Large deployment and the infrastructure held tight. However, if you can wait another business day or two, the next PR will contain a couple of updates I think you'll want to see.

Currently the template deploys Moodle 3.5 with PHP 7.0.3. We're testing a couple changes that'll deploy Moodle 3.9 with PHP 7.4 on Ubuntu 18.04. In addition, looking to clean up the deployment code to handle the stuff discussed in this thread (although this isn't a deal-breaker with the workaround I just proposed in this reply).

**Comment by joseluisrc** [comment]
Since the /moodle/ folder and all of its content is not writeable by the azureadmin user, it's impossible to setup new SSL certificate, or to edit Moodle code.

I'll try to find other solutions in the meantime.

Thanks!

**Comment by UmakanthOS** [comment]
For all operations on that /moodle directory, use

sudo -u www-data <whatever command/op> 

The azureadmin (or whatever azure username, it's azureadmin by default) versus the owner of the Moodle directory (webuser or apacheuser or www-data) isn't specific to Moodle. That's just proper Linux/Unix usage. [More information](https://docs.moodle.org/39/en/Security_recommendations#Most_secure.2Fparanoid_file_permissions) from Moodle directly.

**Comment by joseluisrc** [comment]
I'll test it out.

**Comment by UmakanthOS** [comment]
Please reopen this issue if there's still a concern.
