### ISSUE TITLE
VMSS mount premium disk max share

### ISSUE THREAD

**Issue by cenon4dno** [Azure/Moodle#198]
Hi,

I would like to know what is the maximum instance count on VMSS that could mount the premium disk on the controller. We are expecting to have a large number of users (around 10-100K concurrent users), we would like to know if for example we have 20 instances in VMSS that it will still work. As far as I know, there is a max share limit for the premium disk.

**Comment by UmakanthOS** [comment]
Hello @cenon4dno,

Apologies for the late response. VMSS on Azure supports upto 1000 instances. The template by default limits to 20 instances maximum that you can edit at deployment time (autoscaleVmCountMax) and change the 20 number to whatever you wish. To answer your question, 20 will work fine.
