### ISSUE TITLE
Why is the database on a public subnet?

### ISSUE THREAD

**Issue by rgardler** [Azure/Moodle#20]
According to the diagram in the readme the database is exposed on a public subnet, why is this? Wouldn't it be better to have it on a private network?

**Comment by hosungsmsft** [comment]
My understanding is that it has been always the case, and being addressed by the [Virtual Network Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). It wasn't available on the region I wanted with Azure SQL when I needed earlier, but it seems like at least Azure SQL is available as preview for this feature in all regions. Not sure when MySQL & Postgres will be supported.

**Comment by rgardler** [comment]
OK, so it's a "feature" not a "bug" I'll change the labels and drop to P1 as it seems we can't do anything about it right now.

**Comment by hosungsmsft** [comment]
Still, I think the template should be enhanced so that the database endpoint IP is not exposed to world (0.0.0.0-255.255.255.255), which is the current DB firewall setting. I'm not sure, though, how easy it would be to pass the obtained public IP of the load balancer to the firewall rule.

**Comment by rgardler** [comment]
This was closed due to a commit message that said it "partially fixes", so re-opening. 

@hosung having "fixes #issue_number" in a commit message will close the issue, so if it is a partial fix you need a different note (e.g. "applies to #" or something similar)

**Comment by rgardler** [comment]
OK, so it's not a "partial fix"? I only re-opened because of the word "partial". Happy to close again.

**Comment by hosungsmsft** [comment]
I said it's "partial" in that the issue statement is "Why the database is on a public subnet?" and this fix doesn't move the DB to the private vnet using the Azure vnet service endpoints feature (which is not available for Azure MySQL/PostgreSQL for now). It still configures the DB on an Azure public IP (we really don't have a separate public subnet in our deployment), but all access to the DB is rejected except for our 2 public IP addresses (from the VMSS load balancer and the controller VM).

**Comment by nimojg-microsoft** [comment]
VNET Service endpoints for MySQL and PostgreSQL are now in preview - https://azure.microsoft.com/en-us/blog/vnet-service-endpoints-for-azure-database-services-for-mysql-and-postgresql-in-preview/ 

Should we reopen this issue? Think it might be a good one for the community to address.

**Comment by nimojg-microsoft** [comment]
@hosungsmsft  Just an FYI - VNet Service endpoints are now GA in case this work is still planned. Currently there is no open issue for this in case we want to reopen this.
