### ISSUE TITLE
Default apache landing page after correctly installing certificates and restarting vmss on Maximum installation

### ISSUE THREAD

**Issue by joseluisrc** [Azure/Moodle#201]
Good morning.

After deploying the Maximum size template, the first thing I did was generate the CSR and install the CRT and KEY files in /moodle/certs/[nginx.crt, nginx.key]. Both files are owned by www-data and have 660 file permissions.

Previous to this, I checked that Moodle was running.

I executed sudo /usr/local/bin/update_last_modified_time.moodle_on_azure.sh, and, after restarting the vmss, I got the default Apache landing page.

No other changes have been made to the source code or Moodle config.

Any help would be appreciated.

**Comment by joseluisrc** [comment]
I have another Maximum deployment.

1. On a fresh installation, I restarted the vmss and it worked correctly.
2. I ran /usr/local/bin/update_last_modified_time.moodle_on_azure.sh with no changes done to the server and got the same problem as the original post.

So, it seems the update script is causing this issue, or there could be discrepancies between the controller and vmss that are brought to light after updating.

**Comment by joseluisrc** [comment]
I tried the same steps in a Large deployment with the same results.

Is there a way to revert revert to the previous deployment scripts?

**Comment by ummadisudhakar** [comment]
Noted your concern.We will look into this as it could be an issue as we recently moved to ubuntu 18.04.

**Comment by UmakanthOS** [comment]
@joseluisrc Thanks for flagging this with us. This is fixed now. Please re-open if needed.
