### ISSUE TITLE
VMExtensionCSELinuxTroubleshoot

### ISSUE THREAD

**Issue by Baiazitov** [Azure/Moodle#205]
Hi, This default settings, how i can fixed it? THX
{
  "code": "DeploymentFailed",
  "message": "Как минимум одна операция развертывания ресурса не выполнена. Для получения сведений откройте список операций развертывания. Сведения об использовании: https://aka.ms/DeployOperations.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"Операция ресурса завершилась с окончательным состоянием подготовки \\\"Failed\\\".\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"При обработке расширения \\\"install_moodle\\\" виртуальная машина сообщила об ошибке: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\n\\n[stderr]\\nRAIDPARTITION=/dev/md1p1\\n+ local CREATE_FILESYSTEM=\\n++ scan_for_new_disks '/dev/sda|/dev/sdb'\\n++ local 'BLACKLIST=/dev/sda|/dev/sdb'\\n++ declare -a RET\\n+++ egrep -v '[0-9]$'\\n+++ egrep -v '/dev/sda|/dev/sdb'\\n+++ ls -1 /dev/sda /dev/sda1 /dev/sda14 /dev/sda15 /dev/sdb /dev/sdb1 /dev/sdc /dev/sdd /dev/sde /dev/sdf\\n++ local 'DEVS=/dev/sdc\\n/dev/sdd\\n/dev/sde\\n/dev/sdf'\\n++ for DEV in ${DEVS}\\n++ '[' '!' -b /dev/sdc1 ']'\\n++ RET+='/dev/sdc '\\n++ for DEV in ${DEVS}\\n++ '[' '!' -b /dev/sdd1 ']'\\n++ RET+='/dev/sdd '\\n++ for DEV in ${DEVS}\\n++ '[' '!' -b /dev/sde1 ']'\\n++ RET+='/dev/sde '\\n++ for DEV in ${DEVS}\\n++ '[' '!' -b /dev/sdf1 ']'\\n++ RET+='/dev/sdf '\\n++ echo '/dev/sdc /dev/sdd /dev/sde /dev/sdf '\\n+ local 'DISKS=/dev/sdc /dev/sdd /dev/sde /dev/sdf '\\n+ echo 'Disks are /dev/sdc /dev/sdd /dev/sde /dev/sdf '\\n+ declare -i DISKCOUNT\\n++ wc -w\\n++ echo '/dev/sdc /dev/sdd /dev/sde /dev/sdf '\\n+ local DISKCOUNT=4\\n+ echo 'Disk count is 4'\\n+ '[' 4 = 0 ']'\\n+ '[' 4 -gt 1 ']'\\n+ create_raid0_ubuntu /dev/md1 128 4 /dev/sdc /dev/sdd /dev/sde /dev/sdf\\n+ local RAIDDISK=/dev/md1\\n+ local RAIDCHUNKSIZE=128\\n+ local DISKCOUNT=4\\n+ shift\\n+ shift\\n+ shift\\n+ local 'DISKS=/dev/sdc /dev/sdd /dev/sde /dev/sdf'\\n+ dpkg -s mdadm\\n+ _RET=0\\n+ '[' 0 -eq 1 ']'\\n+ echo 'Creating raid0'\\n+ udevadm control --stop-exec-queue\\n+ mdadm --create /dev/md1 --name=data --level=0 --chunk=128 --raid-devices=4 /dev/sdc /dev/sdd /dev/sde /dev/sdf\\n+ echo yes\\nmdadm: Defaulting to version 1.2 metadata\\nmdadm: array /dev/md1 started.\\n+ udevadm control --start-exec-queue\\n+ mdadm --detail --verbose --scan\\n+ AZMDL_DISK=/dev/md1\\n+ '[' -z '' ']'\\n+ do_partition /dev/md1\\n+ local DISK=/dev/md1\\n+ echo 'Partitioning disk /dev/md1'\\n+ fdisk /dev/md1\\n+ echo -ne 'n\\\\np\\\\n1\\\\n\\\\n\\\\nw\\\\n'\\n+ '[' 0 -ne 0 ']'\\n+ local PARTITION=/dev/md1p1\\n+ echo 'Disk (RAID if multiple unpartitioned disks, or as is if only one unpartitioned disk) is set up, and env var AZMDL_DISK is set to '\\\\''/dev/md1'\\\\'' for later reference'\\n+ '[' -z '' ']'\\n+ echo 'Creating filesystem on /dev/md1p1.'\\n+ mkfs -t ext4 /dev/md1p1\\nmke2fs 1.44.1 (24-Mar-2018)\\n+ mkdir -p /moodle\\n++ tr -d '\\\"'\\n++ awk -F '[= ]' '{print $3}'\\n++ blkid -u filesystem /dev/md1p1\\n+ local UUID=877f4377-4cb5-46c0-8192-2257dd19b9b6\\n+ add_local_filesystem_to_fstab 877f4377-4cb5-46c0-8192-2257dd19b9b6 /moodle\\n+ local UUID=877f4377-4cb5-46c0-8192-2257dd19b9b6\\n+ local MOUNTPOINT=/moodle\\n+ grep -q -s 877f4377-4cb5-46c0-8192-2257dd19b9b6 /etc/fstab\\n+ _RET=1\\n+ '[' 1 -eq 0 ']'\\n+ LINE='\\\\nUUID=877f4377-4cb5-46c0-8192-2257dd19b9b6 /moodle ext4 defaults,noatime 0 0'\\n+ echo -e '\\\\nUUID=877f4377-4cb5-46c0-8192-2257dd19b9b6 /moodle ext4 defaults,noatime 0 0'\\n+ echo 'Mounting disk /dev/md1p1 on /moodle'\\n+ mount /moodle\\n+ configure_nfs_server_and_export /moodle\\n+ local MOUNTPOINT=/moodle\\n+ echo 'Installing nfs server...'\\n+ apt install -y nfs-kernel-server\\n\\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.\\n\\n+ echo 'Exporting /moodle...'\\n+ grep -q -s '^/moodle' /etc/exports\\n+ _RET=1\\n+ '[' 1 = 0 ']'\\n+ echo -e '\\\\n/moodle   *(rw,sync,no_root_squash)'\\n+ systemctl restart nfs-kernel-server.service\\n+ sudo apt-get -y update\\n+ sudo apt-get -y --force-yes install rsyslog git\\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\\n+ '[' nfs = gluster ']'\\n+ '[' nfs = azurefiles ']'\\n+ '[' mysql = mysql ']'\\n+ sudo apt-get -y --force-yes install mysql-client\\ndebconf: unable to initialize frontend: Dialog\\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\\ndebconf: falling back to frontend: Readline\\ndebconf: unable to initialize frontend: Readline\\ndebconf: (This frontend requires a controlling tty.)\\ndebconf: falling back to frontend: Teletype\\ndpkg-preconfigure: unable to re-open stdin: \\nW: --force-yes is deprecated, use one of the options starting with --allow instead.\\n+ '[' false = true -o nfs = azurefiles ']'\\n+ '[' nfs = gluster ']'\\n+ '[' nfs = nfs-ha ']'\\n+ '[' nfs = nfs-byo ']'\\n+ sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa\\n+ sudo apt-get update\\n+ sudo apt-get install software-properties-common\\n\\\".\\r\\n\\r\\nДополнительные сведения об устранении неполадок: https://aka.ms/VMExtensionCSELinuxTroubleshoot. \"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Comment by Baiazitov** [comment]
Enable failed: failed to execute command: command terminated with exit status=1 [stdout] [stderr] to re-open stdin: + config_fail2ban + cat + mkdir -p /moodle + export DEBIAN_FRONTEND=noninteractive + DEBIAN_FRONTEND=noninteractive + '[' nfs = gluster ']' + '[' nfs = nfs ']' + setup_raid_disk_and_filesystem /moodle /dev/md1 /dev/md1p1 + local MOUNTPOINT=/moodle + local RAIDDISK=/dev/md1 + local RAIDPARTITION=/dev/md1p1 + local CREATE_FILESYSTEM= ++ scan_for_new_disks '/dev/sda|/dev/sdb' ++ local 'BLACKLIST=/dev/sda|/dev/sdb' ++ declare -a RET +++ egrep -v '[0-9]$' +++ egrep -v '/dev/sda|/dev/sdb' +++ ls -1 /dev/sda /dev/sda1 /dev/sda14 /dev/sda15 /dev/sdb /dev/sdb1 /dev/sdc /dev/sdd ++ local 'DEVS=/dev/sdc /dev/sdd' ++ for DEV in ${DEVS} ++ '[' '!' -b /dev/sdc1 ']' ++ RET+='/dev/sdc ' ++ for DEV in ${DEVS} ++ '[' '!' -b /dev/sdd1 ']' ++ RET+='/dev/sdd ' ++ echo '/dev/sdc /dev/sdd ' + local 'DISKS=/dev/sdc /dev/sdd ' + echo 'Disks are /dev/sdc /dev/sdd ' + declare -i DISKCOUNT ++ wc -w ++ echo '/dev/sdc /dev/sdd ' + local DISKCOUNT=2 + echo 'Disk count is 2' + '[' 2 = 0 ']' + '[' 2 -gt 1 ']' + create_raid0_ubuntu /dev/md1 128 2 /dev/sdc /dev/sdd + local RAIDDISK=/dev/md1 + local RAIDCHUNKSIZE=128 + local DISKCOUNT=2 + shift + shift + shift + local 'DISKS=/dev/sdc /dev/sdd' + dpkg -s mdadm + _RET=0 + '[' 0 -eq 1 ']' + echo 'Creating raid0' + udevadm control --stop-exec-queue + mdadm --create /dev/md1 --name=data --level=0 --chunk=128 --raid-devices=2 /dev/sdc /dev/sdd + echo yes mdadm: Defaulting to version 1.2 metadata mdadm: array /dev/md1 started. + udevadm control --start-exec-queue + mdadm --detail --verbose --scan + AZMDL_DISK=/dev/md1 + '[' -z '' ']' + do_partition /dev/md1 + local DISK=/dev/md1 + echo 'Partitioning disk /dev/md1' + fdisk /dev/md1 + echo -ne 'n\np\n1\n\n\nw\n' + '[' 0 -ne 0 ']' + local PARTITION=/dev/md1p1 + echo 'Disk (RAID if multiple unpartitioned disks, or as is if only one unpartitioned disk) is set up, and env var AZMDL_DISK is set to '''/dev/md1''' for later reference' + '[' -z '' ']' + echo 'Creating filesystem on /dev/md1p1.' + mkfs -t ext4 /dev/md1p1 mke2fs 1.44.1 (24-Mar-2018) + mkdir -p /moodle ++ tr -d '"' ++ awk -F '[= ]' '{print $3}' ++ blkid -u filesystem /dev/md1p1 + local UUID=a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 + add_local_filesystem_to_fstab a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 /moodle + local UUID=a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 + local MOUNTPOINT=/moodle + grep -q -s a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 /etc/fstab + _RET=1 + '[' 1 -eq 0 ']' + LINE='\nUUID=a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 /moodle ext4 defaults,noatime 0 0' + echo -e '\nUUID=a9b492f1-4c00-4a7a-9e9d-cf2ce1084ef8 /moodle ext4 defaults,noatime 0 0' + echo 'Mounting disk /dev/md1p1 on /moodle' + mount /moodle + configure_nfs_server_and_export /moodle + local MOUNTPOINT=/moodle + echo 'Installing nfs server...' + apt install -y nfs-kernel-server WARNING: apt does not have a stable CLI interface. Use with caution in scripts. + echo 'Exporting /moodle...' + grep -q -s '^/moodle' /etc/exports + _RET=1 + '[' 1 = 0 ']' + echo -e '\n/moodle *(rw,sync,no_root_squash)' + systemctl restart nfs-kernel-server.service + sudo apt-get -y update + sudo apt-get -y --force-yes install rsyslog git W: --force-yes is deprecated, use one of the options starting with --allow instead. + '[' nfs = gluster ']' + '[' nfs = azurefiles ']' + '[' mysql = mysql ']' + sudo apt-get -y --force-yes install mysql-client debconf: unable to initialize frontend: Dialog debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.) debconf: falling back to frontend: Readline debconf: unable to initialize frontend: Readline debconf: (This frontend requires a controlling tty.) debconf: falling back to frontend: Teletype dpkg-preconfigure: unable to re-open stdin: W: --force-yes is deprecated, use one of the options starting with --allow instead. + '[' false = true -o nfs = azurefiles ']' + '[' nfs = gluster ']' + '[' nfs = nfs-ha ']' + '[' nfs = nfs-byo ']' + sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa + sudo apt-get update + sudo apt-get install software-properties-common

**Comment by UmakanthOS** [comment]
Flagging with @ummadisudhakar and @asw101.

Thank you @Baiazitov - we'll see if we can debug this.

**Comment by ummadisudhakar** [comment]
@Baiazitov Is this is the fully configurable deployment and what options you have selected?or its any of the predefined templates?
Can you throw some light on this?

**Comment by Baiazitov** [comment]
![изображение](https://user-images.githubusercontent.com/63315143/90255237-aed07800-de4c-11ea-8c28-1dcef4b77171.png)
![изображение](https://user-images.githubusercontent.com/63315143/90255268-b859e000-de4c-11ea-874d-c8043753a8c5.png)
![изображение](https://user-images.githubusercontent.com/63315143/90255292-c0198480-de4c-11ea-9d63-76127248cfe1.png)
![изображение](https://user-images.githubusercontent.com/63315143/90255319-c9a2ec80-de4c-11ea-869e-78e54f5da167.png)
![изображение](https://user-images.githubusercontent.com/63315143/90255330-cf003700-de4c-11ea-92f2-7bbba820a535.png)
Thanks, for fast answer... I choose default templates

**Comment by scipiotech** [comment]
when using the max deployment in a brand-new resource group I get the following error:

Enable failed: failed to execute command: command terminated with exit status=1 [stdout] [stderr] erVolName":"data","nfsByoIpExportPath":"","nfsHaLbIP":"172.31.2.100","nfsHaExportPath":"/drbd/data","fileServerDiskSize":1024},"phpProfile":{"phpVersion":"7.4"}}' + export storageAccountType= + storageAccountType= ++ jq -r .fileServerProfile.fileServerDiskSize ./helper_functions.sh: line 66: jq: command not found ++ echo '{"siteProfile":{"siteURL":"lb-dcrwyh.eastus.cloudapp.azure.com","httpsTermination":"VMSS","thumbprintSslCert":"None","thumbprintCaCert":"None"},"moodleProfile":{"version":"MOODLE_38_STABLE","dbName":"moodle","dbUser":"moodle","dbUserAzure":"moodle@mysql-dcrwyh","dbPassword":"9#36^rwyhwrxmERCQ","adminPassword":"XLwyhwrxm,1*8","storageAccountName":"absdcrwyhaf","storageAccountKey":"GpHlY/KWXduXZBUILYjINqozlzqduBYtIH/HiMWhImn3Jq+JcNsgX+qVdbN+GDOYqFMKPREMJloAOzxiDkNy0A==","storageAccountType":"Premium_LRS","redisDns":"redis-dcrwyh.redis.cache.windows.net","redisKey":"K1d13cN8QXgETaIM12wDMM4TiuJbZCEYYQh95WDJLQs=","elasticVm1IP":"172.31.5.20","installO365pluginsSwitch":false,"installObjectFsSwitch":false,"installGdprPluginsSwitch":false,"searchType":"elastic","azureSearchKey":"None","azureSearchNameHost":"azure-search-dcrwyh.search.windows.net","tikaVmIP":"none","syslogServer":"controller-vm-dcrwyh","webServerType":"nginx","htmlLocalCopySwitch":true},"dbServerProfile":{"type":"mysql","fqdn":"mysql-dcrwyh.mysql.database.azure.com","adminLogin":"dbadmin","adminLoginAzure":"dbadmin@mysql-dcrwyh","adminPassword":"6dcrwyhwrxm*7PFIWB","mssqlDbServiceObjectiveName":"S1","mssqlDbEdition":"Standard","mssqlDbSize":"250GB"},"fileServerProfile":{"type":"azurefiles","nfsVmName":"controller-vm-dcrwyh","glusterVmName":"gluster-vm-dcrwyh0","glusterVolName":"data","nfsByoIpExportPath":"","nfsHaLbIP":"172.31.2.100","nfsHaExportPath":"/drbd/data","fileServerDiskSize":1024},"phpProfile":{"phpVersion":"7.4"}}' + export fileServerDiskSize= + fileServerDiskSize= ++ jq -r .phpProfile.phpVersion ./helper_functions.sh: line 67: jq: command not found ++ echo '{"siteProfile":{"siteURL":"lb-dcrwyh.eastus.cloudapp.azure.com","httpsTermination":"VMSS","thumbprintSslCert":"None","thumbprintCaCert":"None"},"moodleProfile":{"version":"MOODLE_38_STABLE","dbName":"moodle","dbUser":"moodle","dbUserAzure":"moodle@mysql-dcrwyh","dbPassword":"9#36^rwyhwrxmERCQ","adminPassword":"XLwyhwrxm,1*8","storageAccountName":"absdcrwyhaf","storageAccountKey":"GpHlY/KWXduXZBUILYjINqozlzqduBYtIH/HiMWhImn3Jq+JcNsgX+qVdbN+GDOYqFMKPREMJloAOzxiDkNy0A==","storageAccountType":"Premium_LRS","redisDns":"redis-dcrwyh.redis.cache.windows.net","redisKey":"K1d13cN8QXgETaIM12wDMM4TiuJbZCEYYQh95WDJLQs=","elasticVm1IP":"172.31.5.20","installO365pluginsSwitch":false,"installObjectFsSwitch":false,"installGdprPluginsSwitch":false,"searchType":"elastic","azureSearchKey":"None","azureSearchNameHost":"azure-search-dcrwyh.search.windows.net","tikaVmIP":"none","syslogServer":"controller-vm-dcrwyh","webServerType":"nginx","htmlLocalCopySwitch":true},"dbServerProfile":{"type":"mysql","fqdn":"mysql-dcrwyh.mysql.database.azure.com","adminLogin":"dbadmin","adminLoginAzure":"dbadmin@mysql-dcrwyh","adminPassword":"6dcrwyhwrxm*7PFIWB","mssqlDbServiceObjectiveName":"S1","mssqlDbEdition":"Standard","mssqlDbSize":"250GB"},"fileServerProfile":{"type":"azurefiles","nfsVmName":"controller-vm-dcrwyh","glusterVmName":"gluster-vm-dcrwyh0","glusterVolName":"data","nfsByoIpExportPath":"","nfsHaLbIP":"172.31.2.100","nfsHaExportPath":"/drbd/data","fileServerDiskSize":1024},"phpProfile":{"phpVersion":"7.4"}}' + export phpVersion= + phpVersion= + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + echo + check_fileServerType_param + local fileServerType= + '[' '' '!=' gluster -a '' '!=' azurefiles -a '' '!=' nfs -a '' '!=' nfs-ha -a '' '!=' nfs-byo ']' + echo 'Invalid fileServerType () given. Only '\''gluster'\'', '\''azurefiles'\'', '\''nfs'\'', '\''nfs-ha'\'' or '\''nfs-byo'\'' are allowed. Exiting' + exit 1

**Comment by ummadisudhakar** [comment]
@scipiotech We will take a look at it.

**Comment by ummadisudhakar** [comment]
@Baiazitov We are testing it and found an issue.In a day or 2 it will be fixed.

**Comment by ummadisudhakar** [comment]
@scipiotech @Baiazitov  you can try now.

**Comment by UmakanthOS** [comment]
@Baiazitov Closing. Please re-open if you still see an issue around this topic.
