### ISSUE TITLE
Configurtion recomendations

### ISSUE THREAD

**Issue by Zhuich** [Azure/Moodle#213]
Hi!
Our local Moodle installation now provides a daily load of 30000-40000 requests and 3000-4000 unique logins. In total, about 100,000 users are registered in the system.
We are interested in providing a load 3 times greater than the one we are currently providing.
What scalable and balanced over VM's in the same region Moodle configuration with High Availability do you recommend?
Also, if possible, share your experience in maintaining such systems. For example, how to solve the problem of deleting an unnecessary course with 3000 students enrolled. In the current configuration the unenrollment of 3000 users is a half-hour continuous transaction over user and their enrollments databases.

**Comment by UmakanthOS** [comment]
Hello @Zhuich, I'm pretty late in responding but can you share more about your deployment and if you still are having challenges with your Moodle deployment...
