### ISSUE TITLE
Provide support for Azure Search

### ISSUE THREAD

**Issue by rgardler** [Azure/Moodle#22]
The current templates (optionally) deploys an Elastic Search cluster. This adds 3 VMs to the overall cost of the template. By adding Azure Search we should be able to provide better functionality with a lower maintenance overhead and lower cost.

**Comment by nimojg-microsoft** [comment]
An Azure Search plugin is available now here: https://github.com/catalyst/moodle-search_azure 
We are currently evaluating if we should replace the dependency on Apache Tika by Indexing Documents in Azure Blob Storage with Azure Search (https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage)

**Comment by rgardler** [comment]
[Moving some notes from @nimojg-microsoft  on #64 

Here is the link on GitHub https://github.com/catalyst/moodle-search_azure and it is also in the Moodle plugin directory here: https://moodle.org/plugins/search_azure

Here is the ARM Quickstart for having an Azure Search Service: https://azure.microsoft.com/en-us/resources/templates/101-azure-search-create/

**Comment by hosungsmsft** [comment]
Fixed by #81
