### ISSUE TITLE
Error: cache/Unable to load the cache configuration file

### ISSUE THREAD

**Issue by koconder** [Azure/Moodle#222]
After some use the Moodle install starts to show "cache/Unable to load the cache configuration file", using the smallest size Azure deployment. Tried everything I know to clean/fix but need to rebuild the VM and then the same issue re-occurs.

**Comment by asift91** [comment]
@koconder Please note that Redis Cache is available only for Large and Maximum size deployments.

**Comment by UmakanthOS** [comment]
@koconder Any other errors you can share? Will see if I can replicate it on my end...

**Comment by Mambo87780383** [comment]
Salut, lors de l'installation de Moodle 3.10 à chaque fois je reçois cette erreur la je ne sais comment la résoudre svp besoin d'aide cela fait maintenant trois jour que je suis sans réponse svp voici l'erreur ci-dessous

fatal error: uncaught cache_exception: cache/invalid cache configuration file in c:\xampp\htdocs\moodle\cache\classes\config.php:339 stack trace: #0 c:\xampp\htdocs\moodle\cache\classes\config.php(138): cache_config->include_configuration() #1 c:\xampp\htdocs\moodle\cache\disabledlib.php(323): cache_config->load(false) #2 c:\xampp\htdocs\moodle\cache\classes\factory.php(457): cache_factory_disabled->create_config_instance(true) #3 c:\xampp\htdocs\moodle\cache\disabledlib.php(218): cache_factory->create_definition('core', 'htmlpurifier') #4 c:\xampp\htdocs\moodle\cache\disabledlib.php(254): cache_factory_disabled->create_definition('core', 'htmlpurifier') #5 c:\xampp\htdocs\moodle\cache\classes\loaders.php(182): cache_factory_disabled->create_cache_from_definition('core', 'htmlpurifier', array) #6 c:\xampp\htdocs\moodle\lib\weblib.php(1804): cache::make('core', 'htmlpurifier', array) #7 c:\xampp\htdocs\moodle\lib\weblib.php(1709): purify_html('
