### ISSUE TITLE
Moodle On Azure

### ISSUE THREAD

**Issue by oscarcames** [Azure/Moodle#223]
Hello,

We are installing the moodle distribution you recommend on Azure, everything is fine, but we cannot change the domain name assigned to moodle by azure with our custom domain name. What is the reason or how can we do so please help. For example; When we set up the private moodle distribution, it gives us a domain name like "https://lb-3fqpgf.westeurope.cloudapp.azure.com/" and we want to change it to our custom domain name like "lms.abc.edu.tr" We want to add ssl. Please provide immediate assistance. Thank you for your interest.

Regards.

Mail Address: adem.coban@idedanismanlik.com.tr

**Comment by SorraTheOrc** [comment]
Please see the documentation folder. There are docs on setting up SSL. To configure the domains name see the siteURL parameter in the template

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by asift91** [comment]
@oscarcames 
At the time of Moodle deployment from GitHub, you can provide your domain name and your SSL only in the [custom deployment template](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FMoodle%2Fmaster%2Fazuredeploy.json).

**Comment by UmakanthOS** [comment]
Closing per prior feedback. Please re-open if SSL setup is still a challenge.
