### ISSUE TITLE
Custom SiteUrl After Installation

### ISSUE THREAD

**Issue by Domdu** [Azure/Moodle#224]
Hi,

We want to change LB public url to our siteurl. We changed all of the variables into moodle config and sync with VMSS instances. But when we request our site, application return "http 301" response to LB url and after that response our site url. 

I check the VMSS extensions and i found setup_webserver.sh. This script take moodle_on_azure_configs_json_path as a parameter. This parameter using in "helper_functions.sh". I found "/var/lib/cloud/instance/moodle_on_azure_configs.json" into our Controller VM. I changed siteURL parameter. And after that reimage instances. But configurations not changed. 

How can we change siteURL variable for VMSS instances?

Best Regards.

**Comment by Domdu** [comment]
I fixed that problem. Thanks

**Comment by AliKarpuzoglu** [comment]
@Domdu  what did you do?
