### ISSUE TITLE
Updating certs does not seem to work

### ISSUE THREAD

**Issue by pagism** [Azure/Moodle#239]
The default template deployment is generating temporary certs for lb-myapp....cloudapp.azure.com.

Documentation states that cert update an be copied to the following files to be ready immediately:

    /moodle/certs/nginx.key: Your certificate's private key
    /moodle/certs/nginx.crt: Your combined signed certificate and trust chain certificate(s).

I've replaced nginx.key and nginx.crt with the new ones, but the site is still using the old ones, is there any other way to update the key and certificate?

thanks

**Comment by SorraTheOrc** [comment]
The documentation also states you need to restart the web frontend for the certs to be updated. Did you take this step?
________________________________

**Comment by pagism** [comment]
thank you, it is not clear from documentation to restart the web frontend
[changing ssl certs](https://github.com/Azure/Moodle/blob/master/docs/Manage.md#changing-the-ssl-cert)

**Comment by SorraTheOrc** [comment]
Thanks for the point there. I was looking at a different documentation on the SSL topic, which is clear. I'll make a quick edit to the one you link to since you are correct it doesn't say it there. I'll also add link to the more details docs.

________________________________

**Comment by pagism** [comment]
Thanks for this, what is the best way to restart the web frontend then?

**Comment by SorraTheOrc** [comment]
Two approached. 1) simply restart the VMs which can be done via the portal. 2) SSH in and restart just the web processes on each machine

If you have more than 1 VM then doing it via portal is safe as fine as it will restart the VMs one after the other rather than all at once and you will not have downtime. The second option is ideal if you only have a single VM as downtime is unavoidable. Restarting just the web service will be faster.
________________________________

**Comment by pagism** [comment]
we are using the maximum template, from the deployment we only have a singe VM which I think is the controller, I can restart nginx there but has no effect, do I have to restart the controller VM from the portal?

**Comment by SorraTheOrc** [comment]
The web front end is the VM Scale Set (VMSS). See the image in the README for a "boxes and lines" version of how it plugs together.
________________________________
