### ISSUE TITLE
PostgreSQL available version and default one

### ISSUE THREAD

**Issue by gianlucawork** [Azure/Moodle#246]
The version 9.6 is the oldest supported by PostgreSQL.org. The current stable released by them is 13.
In Azure Database for PostgreSQL the most recent one is 11.
Should the array postgresVersion in azuredeploy.json be updated to accept current available version in Azure Database for PostgreSQL?
Something like this:

        "postgresVersion": {
            "allowedValues": [
                "9.6",
		 "10",
		 "11"
            ],
            "defaultValue": "11",
            "metadata": {
                "description": "Postgresql version"
            },
            "type": "string"
        },

From this snippet I removed the 9.5 because it results as "retired" from the available versions during resource creation.
Should I also submit this as a pull request? is it better?

**Comment by UmakanthOS** [comment]
Submitting a PR would actually be quite welcome once you've done a bit of testing. 10 and 11 should work but your contribution would be welcome and appreciated.
