### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by nlt6444** [Azure/Moodle#258]
Is it possible to define a custom name to match  our naming conventions? If so how can we achieve this?

Thank you

**Comment by SorraTheOrc** [comment]
All parameters are configurable if you deploy the fully custom solution, see https://github.com/Azure/Moodle/blob/master/docs/Parameters.md for a documentation of all parameters.

If you are a CLI kind of person then https://github.com/Azure/Moodle/blob/master/azuredeploy.json has all the parameters at the start. You can any values using a customer parameters file as described in https://github.com/Azure/Moodle/blob/master/docs/Deploy.md

**Comment by nlt6444** [comment]
Thank you
