### ISSUE TITLE
error while applying plug-in

### ISSUE THREAD

**Issue by lalitm14** [Azure/Moodle#265]
getting following error when trying to apply local_o365 plugin ... please share any guidance to resolve " ... Outdated component cache file defined in $CFG->alternative_component_cache, can not continue ..."

**Comment by SorraTheOrc** [comment]
Can you please provide repro steps so that we can look at the actual error here. It's not clear that this is a problem with these templates.

**Comment by lalitm14** [comment]
thanks ... I figured by editing  /moodle/html/moodle/config.php file to comment out the line with variable $CFG_alternative_component, worked. I have Moodle course showing in my Teams, but everything pops into a new browser, how to fix that to keep all the interface coming in the S Teams iframe?
