### ISSUE TITLE
Adding application gateway after deployment.

### ISSUE THREAD

**Issue by nlt6444** [Azure/Moodle#267]
Hello, I deployed the mid-size template several months ago.  We now have a requirement to add an application gateway. Do any changes need to be made to the nginx conf  in order to work with the app gateway? Ultimately we would like to bypass the lb and use vmss as the backend pool.

**Comment by UmakanthOS** [comment]
Hello @nlt6444, thanks for bringing it up. If you're going to terminate TLS at Application Gateway and have communication between Application Gateway and VMSS be HTTP, you don't need to do anything else. Have you had a chance to look at https://github.com/Azure/Moodle/blob/d250722a498dec30eb64cb1c81e5c9b3799f2270/nested/appgw.json ?

**Comment by nlt6444** [comment]
Thank you.
