### ISSUE TITLE
Allow choice of NFS over Gluster

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/Moodle#27]
The /moodle directory is shared out to frontend VMs through the replicated Gluster cluster for high availability as well. However, we are hearing that the Gluster performance is not very good and asked about other options, like copying the static content over to the local file system. I think we should at least try to allow the choice of NFS over Gluster in the template. We might use one dedicated VM for the NFS host, but also could consider utilizing the jumpbox VM. Of course we should also consider the cron job scalability on the jumbbox as well, in that case.

**Comment by rgardler** [comment]
Agreed. Although to evaluate the performance of Gluster vs NFS we'd want to make sure we have some load testing scripts in place first.

Another option that might be worth evaluating is Azure Files for the PHP code.

(flagging the Cron scalability issue #23 as you mention it in your original post)
