### ISSUE TITLE
Allow choice of not installing ElasticSearch plugin and not deploying VMs

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/Moodle#29]
Currently the template installs the ElasticSearch plugin and 3 VMs for that. It would be good to allow choice of not installing the plugin and deploying the 3 VMs, mainly for customers who don't want the ElasticSearch (or at least load testing scenarios where elastic search is not used/needed).

It'd be interesting how to seamlessly add the elastic search VMs and configs after the initial cluster deployment without the feature selected.

**Comment by rgardler** [comment]
+1, related to this is the potential to provide alternative search solutions. SOLR is popular and Azure Search would reduce both the overhead and cost of running Moodle cluster by moving a component that is rarely customized into a SaaS offering.
