### ISSUE TITLE
Azure SQL Database Managed Instance

### ISSUE THREAD

**Issue by nimojg-microsoft** [Azure/Moodle#46]
Does the MS SQL implementation work with Azure SQL Database Managed Instance? https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance

**Comment by rgardler** [comment]
I do not believe so, @hosungsmsft can you confirm? Should we use managed instance?

**Comment by hosungsmsft** [comment]
I don't think so. It's just from my cursory look at the [tutorial](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-tutorial-portal). FYI, this service currently requires manual whitelisting of the subscription (as described at the top of the tutorial), being in its gated public preview state. The tutorial also states that SQL MI requires a virtual network, which our current MS SQL template doesn't support. So to support SQL MI, it looks like we'll need to do some nontrivial updates on our MS SQL template.
