### ISSUE TITLE
Allow option of Azure Load Balancer Standard SKU

### ISSUE THREAD

**Issue by nimojg-microsoft** [Azure/Moodle#63]
Not sure if the deployment would benefit from this or if the Basic SKU is good enough: https://azure.microsoft.com/en-us/blog/the-new-azure-load-balancer-10x-scale-increase/

**Comment by rgardler** [comment]
The basic SKU would be sufficient for many workloads, but it is entirely possible that the Standard SKU will be required in larger deployments. We'd certainly accept a pull request to enable this option.
