### ISSUE TITLE
Allow installation of Azure Search plugin and configuration of Azure Search by default

### ISSUE THREAD

**Issue by nimojg-microsoft** [Azure/Moodle#64]
Here is the link on GitHub https://github.com/catalyst/moodle-search_azure and it is also in the Moodle plugin directory here: https://moodle.org/plugins/search_azure 

Here is the ARM Quickstart for having an Azure Search Service: https://azure.microsoft.com/en-us/resources/templates/101-azure-search-create/

**Comment by rgardler** [comment]
Closing as a duplicate of #22
