### ISSUE TITLE
PROPOSAL: Make HTML Local Copy true by default

### ISSUE THREAD

**Issue by rgardler** [Azure/Moodle#67]
Now that we have run a series of load tests against the new ["local copy" feature](https://github.com/Azure/Moodle/blob/91313a9df71ef1c8303d450189fbb0708b7d86a8/azuredeploy.json#L61) for PHP files should we turn it on by default?

**Comment by hosungsmsft** [comment]
I wouldn't yet say we have run a series of tests with that setting turned on, but we can certainly pick that up anyway. PR/commit welcome for that change... :)

**Comment by hosungsmsft** [comment]
Fixed by #69
