### ISSUE TITLE
Architecture diagram needs updating

### ISSUE THREAD

**Issue by nimojg-microsoft** [Azure/Moodle#83]
Architecture diagram should be updated to show latest deployment configurations (MS SQL, Azure Search etc.).

**Comment by nimojg-microsoft** [comment]
In terms of timing, I think we will want this complete before our webinar on May 1st

**Comment by meepster-nz** [comment]
Hi Hosung.
My name is Matt Dawson and I am the frontend designer here at Catalyst AU.
Andrew Boag has informed me you need changes to the diagram? Can you get me up to speed and what you are wanting exactly? Cheers

**Comment by meepster-nz** [comment]
Hi Hosung.
I will try and update the diagram as per instructions though it always a hard to get exact unless a wireframe is shown. I will get an updated version based on your description shortly.
Cheers

**Comment by hosungsmsft** [comment]
Thanks Matt. Yes it's not easy to get exact, and we'd like at least to reflect the correct architecture and the recent updates. We'd need the diagram to be in PPT for future updates, so let us know if there's any issue with that ask. Thanks!

**Comment by meepster-nz** [comment]
![diagram-update](https://user-images.githubusercontent.com/8229423/39456481-0882524e-4d2a-11e8-994e-90ddfad82840.png)

Let me know if i am on the right track.

**Comment by rgardler** [comment]
Diagram updated
