### ISSUE TITLE
Add "simple ci" to run in all branches, full deployment tests only on specific scenarios.

### ISSUE THREAD

**Issue by roperto** [Azure/Moodle#90]
Derived form comments on #77 

A full CI is expensive to run for every commit/push in any branch, but it is interesting to still run other tests (linting/validation).

**Comment by roperto** [comment]
@hosungsmsft  -- I think having a ENV is a good option. We could define a envbar with comma-separated list of branches where full-ci should run. Is that your idea?

Just pitching an idea: the main usecase I see for myself would be wanting to run the deployment test at some specific points during the development. To address that, we could even implement detecting "[full ci]" in the commit, similar to what [skip ci] does -- see https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by hosungsmsft** [comment]
Yes, having an env var specifying all branches where full CI should be run was what I had in mind.

Your "[full ci]" idea feels also useful, and if it's not too hard to implement that, yes, we'd like that too. Thanks for your great suggestion!
