### ISSUE TITLE
How do I upgrade from basic to standard LB SKU?

### ISSUE THREAD

**Issue by SorraTheOrc** [Azure/Moodle#97]
By default the template creates a basic SKU LB. Some users have asked if it would be possible to upgrade this to a standard SKU LB. The instructions below are a starter for instructions on how to do this, but these are written for a different workload and need "translating" to the LAMP stack here.

2.  Create a Ubuntu VM and install haproxy: sudo apt-get install haproxy
3.  Add the following contents to /etc/haproxy/haproxy.cfg
listen bravo1
    bind *:80 # or any other ports you want to redirect.
    mode tcp
    server bravo1 <standard-sku-public-ip>:80
 
listen bravo2
    bind *:443
    mode tcp
    server bravo2 <standard-sku-public-ip>:443
4.       Restart haproxy: sudo service haproxy restart
5.       Create two rules in the VM's NSG to allow traffic to the port 80 and 443.
6.       Redeploy CF to change from the basic SKU LB to the standard SKU LB.
7.       Delete the basic SKU LB, then the basic SKU public IP gets detached.
8.       Change the public IP of the proxy VM to the basic SKU public IP.
9.       The traffic to the basic SKU public IP will be forwarded to the Standard SKU public IP. Run "tail -f /var/log/haproxy.log" to check the traffic forwarding.
10.   After the DNS records are propagated globally, the proxy VM can be deleted safely.

**Comment by UmakanthOS** [comment]
A Standard LB is the default option now and we are looking at better integration with L7 Load balancers. Closing as this is no longer relevant (unless customer forces the use of a Basic LB through the fully customizable option). Please re-open if you disagree..
